apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: runner-system

resources:
- ./common
- ./runner-control

images:
- name: runner-control
  newName: ${artifact_registry_path}runner-control
  newTag: 2025-11-14.2
labels:
- includeSelectors: true
  pairs:
    app: runner-control
    code-owner: runwhen
