apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: worksync-controller
    control-plane: controller-manager
  name: worksync-system
  annotations: 
    kustomize.toolkit.fluxcd.io/prune: disabled