apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-controller
  namespace: worksync-system
imagePullSecrets:
  - name: gcp-registry-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-leader-election-role
  namespace: worksync-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: worksync-controller
  name: worksync-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - runwhen.com
  resources:
  - personas
  - runbooks
  - slis
  - slos
  - slxs
  - tutorials
  - workflows
  - workspaces
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - personas/status
  - runbooks/status
  - slis/status
  - slos/status
  - slxs/status
  - tutorials/status
  - workflows/status
  - workspaces/status
  verbs:
  - get
- apiGroups:
  - runwhen.com
  resources:
  - worksyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - worksyncs/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - worksyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets/status
  - gitrepositories/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-leader-election-rolebinding
  namespace: worksync-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worksync-leader-election-role
subjects:
- kind: ServiceAccount
  name: worksync-controller
  namespace: worksync-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: worksync-proxy-role
subjects:
- kind: ServiceAccount
  name: worksync-controller
  namespace: worksync-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: worksync-controller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worksync-controller
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: worksync-controller
  name: worksync-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: worksync-manager-role
subjects:
- kind: ServiceAccount
  name: worksync-controller
  namespace: worksync-system
