apiVersion: v1
kind: Service
metadata:
  name: agentfarm
  namespace: backend-services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: agentfarm
  type: ClusterIP
