apiVersion: v1
kind: Service
metadata:
  name: modelsync
  namespace: backend-services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: modelsync
  type: ClusterIP
