apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-papi
  labels: 
    app: papi
spec:
  provider: vault
  secretObjects:
    - secretName: papi-secrets
      type: Opaque
      data:
        - objectName: gitlab_oauth_app_client_id
          key: gitlab_oauth_app_client_id
        - objectName: gitlab_oauth_app_client_secret
          key: gitlab_oauth_app_client_secret
        - objectName: rw_shared_llm_vkey
          key: rw_shared_llm_vkey
  parameters:
    vaultAddress: "${vault_address}"
    vaultKubernetesMountPath: kubernetes
    roleName: "shared_secrets"
    objects: |
      - objectName: "secrets.py"
        secretPath: "shared/data/secrets"
        secretKey: "secrets.py"
      - objectName: "gitlab_oauth_app_client_id"
        secretPath: "shared/data/gitlab_oauth"
        secretKey: "SOCIAL_ACCOUNT_PROVIDERS_GITLAB_APP_CLIENT_ID"
      - objectName: "gitlab_oauth_app_client_secret"
        secretPath: "shared/data/gitlab_oauth"
        secretKey: "SOCIAL_ACCOUNT_PROVIDERS_GITLAB_APP_CLIENT_SECRET"
      - objectName: "rw_shared_llm_vkey"
        secretPath: "shared/data/litellm-proxy/virtual-keys"
        secretKey: "RW_SHARED_LLM"