apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-slackbot
  labels: 
    app: slackbot
spec:
  provider: vault
  secretObjects:
    - secretName: slackbot-secrets
      type: Opaque
      data:
        - objectName: slack_client_id
          key: slack_client_id 
        - objectName: slack_client_secret
          key: slack_client_secret
        - objectName: slack_signing_secret
          key: slack_signing_secret
        - objectName: fernet_key
          key: fernet_key
  parameters:
    vaultAddress: "${vault_address}"
    vaultKubernetesMountPath: kubernetes
    roleName: "shared_secrets"
    objects: |
      - objectName: "slack_client_id"
        secretPath: "shared/data/slackbot"
        secretKey: "SLACK_CLIENT_ID"
      - objectName: "slack_client_secret"
        secretPath: "shared/data/slackbot"
        secretKey: "SLACK_CLIENT_SECRET"
      - objectName: "slack_signing_secret"
        secretPath: "shared/data/slackbot"
        secretKey: "SLACK_SIGNING_SECRET"
      - objectName: "fernet_key"
        secretPath: "shared/data/slackbot"
        secretKey: "FERNET_KEY"
