apiVersion: v1
kind: Service
metadata:
  name: sobow-search
  namespace: backend-services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: sobow-search
  type: ClusterIP
