apiVersion: apps/v1
kind: Deployment
metadata:
  name: sobow-index
  namespace: backend-services
  labels: 
    app: sobow-index
    code-owner: runwhen
    codecollection.runwhen.com/app: sobow-index
spec:
  selector:
    matchLabels:
      app: sobow-index
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: sobow-index
      labels:
        app: sobow-index
        code-owner: runwhen
        codecollection.runwhen.com/app: sobow-index
    spec:
      serviceAccountName: papi-sa
      initContainers:
      - name: init-wait-for-core-db
        image: busybox:1.28
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: host
        command: ['sh', '-c', "until nslookup $DATABASE_HOST; do echo waiting for core db; sleep 2; done"]
      - name: init-wait-for-migrations
        image: backend-services  # Same image as main container
        workingDir: /project-468/backend-services
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        command: ['/scripts/wait-for-migrations.sh']
        volumeMounts:
        - name: secrets
          mountPath: /project-468/backend-services/shhh
        - name: migration-scripts
          mountPath: /scripts
        envFrom:
        - configMapRef:
            name: papi-env-vars-cm
            optional: true
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: DJANGO_SETTINGS_MODULE
          value: core.settings-migrate
        - name: DATABASE_ENGINE
          value: postgresql
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: password
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: pgbouncer-host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: pgbouncer-port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: dbname
        - name: CACHE_TYPE
          value: "redis-sentinel"
        - name: SENTINEL_HOSTS
          value: "redis-sentinel-headless"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-sentinel
              key: redis-password
      containers:
      - name: sobow-index
        image: backend-services   # Rename this 
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /livez
            port: 8000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 3
          failureThreshold: 9
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 3
          failureThreshold: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 3
          failureThreshold: 10
          periodSeconds: 3
        volumeMounts:
        - name: sobow-index-configs
          readOnly: true
          mountPath: /project-468/backend-services/configs
        - name: secrets
          mountPath: /project-468/backend-services/shhh
        envFrom:
        - configMapRef:
            name: papi-env-vars-cm
            optional: true
        env:  #Set a few env vars useful for debugging
        - name: KUBECONFIG # Pull this out? Shouldn't be needed
          value: /project-468/backend-services/shhh/kubeconfig
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: DJANGO_SETTINGS_MODULE
          value: core.settings-sobow
        - name: FASTAPI_SERVICE
          value: "sobow"
        - name: CACHE_TYPE
          value: "redis-sentinel"
        - name: SENTINEL_HOSTS
          value: "redis-sentinel-headless"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-sentinel
              key: redis-password
        - name: DATABASE_ENGINE
          value: postgresql
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: password
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: pgbouncer-host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: pgbouncer-port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: core-pguser-core
              key: dbname
      volumes:
      - name: sobow-index-configs
        configMap:
          name: sobow-search-configmap
          defaultMode: 0640
          items:
          - key: "index.yaml"
            path: "index.yaml"
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-papi"
      - name: migration-scripts
        configMap:
          name: migration-scripts
          defaultMode: 0755