apiVersion: v1
kind: ConfigMap
metadata:
  name: sobow-search-configmap
  labels:
    app: sobow-search
  namespace: backend-services
data:
  index.yaml: |
    process:
      TASK_BUFFER_SIZE: 150
      TASK_REQUEST_BATCH_SIZE: 25