apiVersion: v1
data:
  webhooks.yaml: |
    ACTIVITIES_SERVICE_URL: http://activities.backend-services.svc.cluster.local
    vault:
      host: http://vault.vault.svc.cluster.local:8200
      authMountPoint: kubernetes
      secretsRole: shared_secrets
      workspaceRole: webhook-read-secrets
kind: ConfigMap
metadata:
  labels:
    app: webhooks
  name: webhooks-configmap
  namespace: backend-services
