---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-control-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-control-rolebinding
subjects:
- kind: ServiceAccount
  name: runner-control
  namespace: runner-system
roleRef:
  kind: Role
  name: runner-control-role
  apiGroup: rbac.authorization.k8s.io
