apiVersion: runwhen.com/v1
kind: CodeCollection
metadata:
  labels:
    codecollection: runwhen-cli-collection
  name: runwhen-cli-collection
  namespace: corestate
spec:
  developmentBranch: main
  homepage: https://runwhen.com
  public: true
  repoURL: https://github.com/runwhen-contrib/rw-cli-codecollection.git
  stable: {}
  watchAllBranches: false
