apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- runner-selfsigned-issuer.yaml
- runner-ca-certificate.yaml
- runner-ca-issuer.yaml
- runner-metrics-ca-certificate.yaml
- runner-metrics-ca-issuer.yaml
