---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: runner-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: runner-selfsigned-issuer-ca
  secretName: runner-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: runner-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
