apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-gitservice
  labels: 
    app: gitservice
  namespace: flux-system
spec:
  provider: vault
  parameters:
    vaultAddress: "${vault_address}"
    vaultKubernetesMountPath: kubernetes
    roleName: "shared_secrets"
    objects: |
      - objectName: "username"
        secretPath: "shared/data/git-service"
        secretKey: "username"
      - objectName: "password"
        secretPath: "shared/data/git-service"
        secretKey: "password"
  secretObjects: 
  - data: 
    - key: username
      objectName: username
    - key: password
      objectName: password
    secretName: gitservice-secret
    type: Opaque
    labels: 
      app: gitservice
