# Support reading of runner secrets generated by corestate within an org and workspace
# For now I'm pulling the the stored approle information for each runner here since corestate is currently doing most of the secret / role management. 
path "org/data/+/workspace/+/system/corestate/*" {
 capabilities = [ "read" ]
}

# Support listing of runner secrets generated by corestate within an org and workspace
path "org/metadata/+/workspace/+/system/corestate/*" {
 capabilities = [ "list" ]
}

# Support management of runner secrets of a workspace provided by runwhen within an org
path "org/data/+/workspace/+/system/runner/*" {
 capabilities =  ["create", "read", "update"]
}
path "org/metadata/+/workspace/+/system/runner/*" {
 capabilities = ["read", "delete", "list"]
}

# Support reading deployment secrets for the runner-system
## I suspect we'll also require a user policy update so we can set these without root
path "runner-system/data/*" {
 capabilities =  ["read"]
}
