---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runwhen-ui
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/ui
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-cluster-cluster-vars
