apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: corestate-controller-manager@${project_id}.iam.gserviceaccount.com
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-controller-manager
  namespace: corestate
imagePullSecrets:
  - name: gcp-registry-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-leader-election-role
  namespace: corestate
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - codecollections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - codecollections/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - codecollections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - codecollectionversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - codecollectionversions/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - codecollectionversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - coderuns
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - coderuns/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - coderuns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - locations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - locations/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - locations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - locationworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - personas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - personas/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - personas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - runbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - runbooks/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - runbooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - slis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - slis/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - slis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - slos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - slos/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - slos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - slxs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - slxs/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - slxs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - personas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - personas/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - personas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runwhen.com
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runwhen.com
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - runwhen.com
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sloth.slok.dev
  resources:
  - prometheusservicelevels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-leader-election-rolebinding
  namespace: corestate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: corestate-leader-election-role
subjects:
- kind: ServiceAccount
  name: corestate-controller-manager
  namespace: corestate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: corestate-manager-role
subjects:
- kind: ServiceAccount
  name: corestate-controller-manager
  namespace: corestate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: corestate
    component: corestate
    controller-manager: corestate
  name: corestate-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: corestate-proxy-role
subjects:
- kind: ServiceAccount
  name: corestate-controller-manager
  namespace: corestate
