---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-corestate
spec:
  provider: vault
  parameters:
    vaultAddress: "${vault_address}"
    vaultKubernetesMountPath: kubernetes
    roleName: "shared_secrets"
    objects: |
      - objectName: "kubeconfig"
        secretPath: "shared/data/platform-kubeconfig"
        secretKey: "kubeconfig"
