apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: corestate

resources:
- namespace.yaml
- sloth-install.yaml
- corestate-crd.yaml
- corestate-sa.yaml
- corestate-csi-secret-class.yaml
- corestate-manager-configmap.yaml
- corestate-service.yaml
- corestate-deployment.yaml
- corestate-configmap.yaml
images:
- name: corestate-controller
  newName: ${artifact_registry_path}corestate-controller
  newTag: feat-fastapi_migration-67daa6e
