apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- runner-mimir-tenant-cm.yaml
- runner-mimir-tenant-deployment.yaml
- runner-mimir-tenant-service.yaml
- runner-mimir-tenant-ingress.yaml
